version: '3'
services:
  db:
    image: mysql
    container_name: mysqlGreatAgain
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=djangoadmin
      - MYSQL_PASSWORD=django
      - MYSQL_DATABASE=monblog
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - db_network

  app:
    restart: always
    build: .
    container_name: djangoGreatAgain
    entrypoint: /start.sh
    volumes:
      - .:/code
      - static-volume:/code/static
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network

  nginx:
    image: nginx
    container_name: nginxGreatAgain
    ports:
      - "3000:8000"
    volumes:
      - static-volume:/code/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  static-volume:
