# Generated by Django 2.2.5 on 2020-01-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0002_auto_20200118_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
