# Generated by Django 2.2.5 on 2020-01-18 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0005_auto_20200118_1709'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plateforme', '0003_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=2500)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
