# Generated by Django 2.2.5 on 2020-01-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
