# Generated by Django 2.2.7 on 2020-01-20 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0006_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
