# Generated by Django 2.2.7 on 2020-01-20 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='expert',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
