# Generated by Django 2.2.7 on 2020-01-20 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_auto_20200120_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
