# Generated by Django 2.2.7 on 2020-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0011_remove_projet_experts'),
        ('expert', '0003_auto_20200120_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='validated_projects',
            field=models.ManyToManyField(to='projet.Projet'),
        ),
    ]
