# Generated by Django 2.2.5 on 2020-01-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0009_projet_financement'),
        ('financeurs', '0002_auto_20200117_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('date_paiement', models.DateTimeField()),
                ('montant', models.FloatField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Projet')),
            ],
        ),
        migrations.AddField(
            model_name='financeur',
            name='paiments',
            field=models.ManyToManyField(to='financeurs.Paiement'),
        ),
    ]
