# Generated by Django 2.2.7 on 2020-01-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copyright', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('somme', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='copyright.Copyright')),
                ('membres', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
