# Generated by Django 2.2.7 on 2020-01-18 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
