# Generated by Django 2.2.7 on 2020-01-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_auto_20200118_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='license',
            new_name='copyright',
        ),
    ]
