# Generated by Django 2.2.7 on 2020-01-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0008_auto_20200119_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='financement',
            field=models.IntegerField(default=0),
        ),
    ]
