# Generated by Django 2.2.7 on 2020-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_auto_20200120_1911'),
        ('projet', '0009_projet_financement'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='experts',
            field=models.ManyToManyField(null=True, to='expert.Expert'),
        ),
    ]
