# Generated by Django 2.2.7 on 2020-01-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0010_projet_experts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='experts',
        ),
    ]
